- hosts: samba_dc
  become: yes

  tasks:

    - name: Install packages
      apt:
        name:
          - samba
          - samba-ad-provision
          - krb5-user
          - winbind
          - dnsutils
        state: present
        update_cache: yes

    - name: Set hostname
      hostname:
        name: labdc2

    - name: Configure hosts file
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost
          192.168.64.20 labdc2.homelab.internal labdc2

    - name: Install static netplan
      copy:
        dest: /etc/netplan/00-installer-config.yaml
        content: |
          network:
            version: 2
            ethernets:
              enp0s1:
                dhcp4: false
                addresses:
                  - 192.168.64.20/24
                routes:
                  - to: default
                    via: 192.168.64.1
                nameservers:
                  addresses:
                    - 192.168.64.10

    - name: Apply netplan
      command: netplan apply
